Adding alwaysShow prop to show item regardless of both filter and maxSuggestions.
anubra266/choc-autocomplete pull request #125
Opened 2022-02-15 00:39 UTC by daliudzius

As it stands, `fixed` is filtered out of the suggestions if these two conditions are met:
- there exists a maxSuggestions limit
- the `fixed` item index > maxSuggestions

My proposal is to keep that functionality but add another prop `alwaysShow` that behaves similar to `fixed` except it shows in suggestions regardless of maxSuggestions limit.

2022-02-16 18:53 UTC, anubra266 requested changes
Let's used the `fixed` prop instead of `alwaysShow`

2022-02-17 05:25 UTC, daliudzius reviewed
added minor wording to readme, and switched alwaysShow functionality to fixed

2022-02-17 05:26 UTC, daliudzius commented
There ya go, much simpler to use `fixed` as you mentioned.

2022-02-17 10:28 UTC, anubra266 approved these changes

2022-02-17 10:28 UTC, merged

2022-02-17 10:31 UTC, anubra266 commented
Available in [v4.17.1](https://github.com/anubra266/choc-autocomplete/releases/tag/v4.17.1)

2022-02-17 10:31 UTC, anubra266 commented
@all-contrubutors please add @daliudzius for code

2022-02-17 10:32 UTC, anubra266 commented
@all-contributors please add @daliudzius for code